name: Tester

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test with Gradle
        run: ./gradlew test
      - name: Coveralls with Gradle
        env:
          repo_token: 5WzTo6eDMB0WZgKiNUfCrvZwsyGlaVRJ1
        run: ./gradlew jacocoTestReport coveralls
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Coverage
        run: ./gradlew jacocoTestReport coveralls
        env:
          CI: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}