name: Tester

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test with Gradle
        run: ./gradlew test
      - name: Coveralls with Gradle
        env:
          repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: ./gradlew jacocoTestReport coveralls